-- Phase 2 provisioning control-plane state. This is additive: shipped Phase 1
-- migrations remain immutable and production data is never rewritten.
CREATE TABLE nodes (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    hostname          TEXT NOT NULL UNIQUE,
    backend           TEXT NOT NULL
                      CHECK (backend IN ('docker', 'hestia', 'fake')),
    status            TEXT NOT NULL DEFAULT 'online'
                      CHECK (status IN ('online', 'draining', 'offline')),
    capacity_sites    INTEGER NOT NULL
                      CHECK (capacity_sites > 0),
    used_sites        INTEGER NOT NULL DEFAULT 0
                      CHECK (used_sites >= 0 AND used_sites <= capacity_sites),
    provider_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_nodes_placement
    ON nodes (status, used_sites, capacity_sites, created_at)
    WHERE status = 'online';

CREATE TABLE sites (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    account_id      UUID NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    node_id         UUID NOT NULL REFERENCES nodes(id),
    domain          TEXT NOT NULL,
    image           TEXT NOT NULL,
    internal_port   INTEGER NOT NULL
                    CHECK (internal_port BETWEEN 1 AND 65535),
    memory_bytes    BIGINT NOT NULL
                    CHECK (memory_bytes >= 67108864),
    nano_cpus       BIGINT NOT NULL
                    CHECK (nano_cpus > 0),
    status          TEXT NOT NULL DEFAULT 'provisioning'
                    CHECK (status IN (
                        'provisioning', 'active', 'suspending', 'suspended',
                        'resuming', 'deleting', 'deleted', 'failed'
                    )),
    idempotency_key TEXT,
    last_error      TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ,
    capacity_released_at TIMESTAMPTZ,
    UNIQUE (domain)
);

CREATE INDEX idx_sites_account_created
    ON sites (account_id, created_at DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_sites_node_status
    ON sites (node_id, status);
CREATE UNIQUE INDEX idx_sites_account_idempotency
    ON sites (account_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL;

CREATE TABLE jobs (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    account_id   UUID REFERENCES accounts(id) ON DELETE SET NULL,
    kind         TEXT NOT NULL
                 CHECK (kind IN (
                     'provision_site', 'delete_site', 'suspend_site',
                     'resume_site', 'cleanup_site', 'reconcile_site'
                 )),
    status       TEXT NOT NULL DEFAULT 'queued'
                 CHECK (status IN ('queued', 'running', 'succeeded', 'failed')),
    attempts     INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    max_attempts INTEGER NOT NULL DEFAULT 5 CHECK (max_attempts > 0),
    run_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    locked_at    TIMESTAMPTZ,
    locked_by    TEXT,
    payload      JSONB NOT NULL,
    last_error   TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_jobs_claim
    ON jobs (run_at, created_at)
    WHERE status = 'queued';
CREATE INDEX idx_jobs_running
    ON jobs (locked_at)
    WHERE status = 'running';
CREATE INDEX idx_jobs_account_created
    ON jobs (account_id, created_at DESC);

-- Only one pending/running operation of a given kind may exist for a site.
-- JSON payloads contain UUID strings generated by the service, never secrets.
CREATE UNIQUE INDEX idx_jobs_active_site_kind
    ON jobs (kind, ((payload ->> 'site_id')))
    WHERE status IN ('queued', 'running')
      AND payload ? 'site_id';
